[project]

name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = 
  "Flask>=2.0",
  "gunicorn>=20.0",
  "python-dotenv>=0.19"

